// ============================================================
// ChainQuest MMO - Game Constants & Definitions
// Job tree, skill definitions, monster data, exp tables
// ============================================================

import type {
  JobDefinition,
  SkillDefinition,
  MonsterDefinition,
  MapDefinition,
  LevelData,
} from "./types";

// ----------------------------------------------------------
// Tick Rate
// ----------------------------------------------------------
export const TICK_RATE_MS = 66; // ~15 TPS
export const INTERPOLATION_DELAY_MS = 100;
export const MAX_INTEREST_RADIUS = 15; // tiles — interest management
export const TILE_SIZE = 32;
export const MAP_WIDTH = 64;
export const MAP_HEIGHT = 64;

// ----------------------------------------------------------
// Job Definitions
// ----------------------------------------------------------

export const JOB_DEFINITIONS: Record<string, JobDefinition> = {
  novice: {
    id: "novice",
    name: "Novice",
    tier: 1,
    parent: null,
    children: ["swordsman", "mage", "archer"],
    primaryStat: "str",
    statGrowth: { str: 1, vit: 1, agi: 1, int: 1, dex: 1, luk: 1 },
    hpPerLevel: 40,
    spPerLevel: 10,
    skillIds: ["auto_attack"],
    advancementLevel: 10,
    advancementBaseLevel: 10,
    icon: "⚔️",
    color: "#94a3b8",
  },
  swordsman: {
    id: "swordsman",
    name: "Swordsman",
    tier: 1,
    parent: "novice",
    children: ["knight"],
    primaryStat: "str",
    statGrowth: { str: 3, vit: 2, agi: 2, int: 0, dex: 1, luk: 1 },
    hpPerLevel: 80,
    spPerLevel: 8,
    skillIds: ["auto_attack", "bash", "provoke"],
    advancementLevel: 40,
    advancementBaseLevel: 25,
    icon: "🗡️",
    color: "#ef4444",
  },
  knight: {
    id: "knight",
    name: "Knight",
    tier: 2,
    parent: "swordsman",
    children: ["lord_knight"],
    primaryStat: "str",
    statGrowth: { str: 4, vit: 3, agi: 2, int: 0, dex: 1, luk: 1 },
    hpPerLevel: 100,
    spPerLevel: 8,
    skillIds: ["auto_attack", "bash", "provoke", "bowling_bash"],
    advancementLevel: 50,
    advancementBaseLevel: 50,
    icon: "🛡️",
    color: "#f97316",
  },
  lord_knight: {
    id: "lord_knight",
    name: "Lord Knight",
    tier: 3,
    parent: "knight",
    children: [],
    primaryStat: "str",
    statGrowth: { str: 5, vit: 4, agi: 3, int: 0, dex: 1, luk: 1 },
    hpPerLevel: 130,
    spPerLevel: 10,
    skillIds: ["auto_attack", "bash", "provoke", "bowling_bash", "magnum_break"],
    advancementLevel: 70,
    advancementBaseLevel: 99,
    icon: "👑",
    color: "#f59e0b",
  },
  mage: {
    id: "mage",
    name: "Mage",
    tier: 1,
    parent: "novice",
    children: ["wizard"],
    primaryStat: "int",
    statGrowth: { str: 0, vit: 1, agi: 1, int: 4, dex: 2, luk: 1 },
    hpPerLevel: 40,
    spPerLevel: 25,
    skillIds: ["auto_attack", "fire_bolt", "frost_diver"],
    advancementLevel: 40,
    advancementBaseLevel: 25,
    icon: "🔮",
    color: "#8b5cf6",
  },
  wizard: {
    id: "wizard",
    name: "Wizard",
    tier: 2,
    parent: "mage",
    children: ["high_wizard"],
    primaryStat: "int",
    statGrowth: { str: 0, vit: 1, agi: 1, int: 5, dex: 3, luk: 1 },
    hpPerLevel: 50,
    spPerLevel: 35,
    skillIds: ["auto_attack", "fire_bolt", "frost_diver", "storm_gust"],
    advancementLevel: 50,
    advancementBaseLevel: 50,
    icon: "⚡",
    color: "#6366f1",
  },
  high_wizard: {
    id: "high_wizard",
    name: "High Wizard",
    tier: 3,
    parent: "wizard",
    children: [],
    primaryStat: "int",
    statGrowth: { str: 0, vit: 1, agi: 2, int: 6, dex: 3, luk: 1 },
    hpPerLevel: 60,
    spPerLevel: 50,
    skillIds: ["auto_attack", "fire_bolt", "frost_diver", "storm_gust", "meteor_storm"],
    advancementLevel: 70,
    advancementBaseLevel: 99,
    icon: "🌟",
    color: "#a78bfa",
  },
  archer: {
    id: "archer",
    name: "Archer",
    tier: 1,
    parent: "novice",
    children: ["hunter"],
    primaryStat: "dex",
    statGrowth: { str: 1, vit: 1, agi: 2, int: 1, dex: 4, luk: 2 },
    hpPerLevel: 55,
    spPerLevel: 12,
    skillIds: ["auto_attack", "double_strafe", "arrow_shower"],
    advancementLevel: 40,
    advancementBaseLevel: 25,
    icon: "🏹",
    color: "#10b981",
  },
  hunter: {
    id: "hunter",
    name: "Hunter",
    tier: 2,
    parent: "archer",
    children: ["sniper"],
    primaryStat: "dex",
    statGrowth: { str: 1, vit: 1, agi: 3, int: 1, dex: 5, luk: 2 },
    hpPerLevel: 65,
    spPerLevel: 15,
    skillIds: ["auto_attack", "double_strafe", "arrow_shower", "blitz_beat"],
    advancementLevel: 50,
    advancementBaseLevel: 50,
    icon: "🦅",
    color: "#34d399",
  },
  sniper: {
    id: "sniper",
    name: "Sniper",
    tier: 3,
    parent: "hunter",
    children: [],
    primaryStat: "dex",
    statGrowth: { str: 1, vit: 1, agi: 4, int: 1, dex: 6, luk: 3 },
    hpPerLevel: 75,
    spPerLevel: 18,
    skillIds: ["auto_attack", "double_strafe", "arrow_shower", "blitz_beat", "falcon_assault"],
    advancementLevel: 70,
    advancementBaseLevel: 99,
    icon: "🎯",
    color: "#059669",
  },
};

// ----------------------------------------------------------
// Skill Definitions
// ----------------------------------------------------------

export const SKILL_DEFINITIONS: Record<string, SkillDefinition> = {
  auto_attack: {
    id: "auto_attack",
    name: "Auto Attack",
    description: "Basic melee or ranged attack",
    damageType: "physical",
    element: "neutral",
    baseDamage: 100,
    statScaling: { str: 1.0 },
    range: 1,
    castTime: 0,
    cooldown: 1000,
    spCost: 0,
    aoe: false,
    aoeRadius: 0,
    canInterrupt: false,
    icon: "⚔️",
    animation: "attack",
  },
  bash: {
    id: "bash",
    name: "Bash",
    description: "A powerful bash that deals 160% ATK damage and may stun",
    damageType: "physical",
    element: "neutral",
    baseDamage: 160,
    statScaling: { str: 1.5 },
    range: 1,
    castTime: 0,
    cooldown: 2500,
    spCost: 8,
    aoe: false,
    aoeRadius: 0,
    statusEffect: "stun",
    statusChance: 15,
    statusDuration: 2000,
    canInterrupt: false,
    icon: "💥",
    animation: "bash",
  },
  provoke: {
    id: "provoke",
    name: "Provoke",
    description: "Taunts an enemy, forcing them to attack you",
    damageType: "physical",
    element: "neutral",
    baseDamage: 0,
    statScaling: {},
    range: 5,
    castTime: 0,
    cooldown: 5000,
    spCost: 5,
    aoe: false,
    aoeRadius: 0,
    statusEffect: "slow",
    statusChance: 100,
    statusDuration: 3000,
    canInterrupt: false,
    icon: "😤",
    animation: "provoke",
  },
  magnum_break: {
    id: "magnum_break",
    name: "Magnum Break",
    description: "AoE fire attack dealing 200% ATK to all nearby enemies",
    damageType: "physical",
    element: "fire",
    baseDamage: 200,
    statScaling: { str: 2.0 },
    range: 1,
    castTime: 0,
    cooldown: 6000,
    spCost: 30,
    aoe: true,
    aoeRadius: 3,
    statusEffect: "burn",
    statusChance: 30,
    statusDuration: 4000,
    canInterrupt: false,
    icon: "🔥",
    animation: "magnum_break",
  },
  bowling_bash: {
    id: "bowling_bash",
    name: "Bowling Bash",
    description: "Charges forward dealing massive AOE damage",
    damageType: "physical",
    element: "neutral",
    baseDamage: 400,
    statScaling: { str: 3.0 },
    range: 3,
    castTime: 500,
    cooldown: 8000,
    spCost: 40,
    aoe: true,
    aoeRadius: 2,
    statusEffect: "stun",
    statusChance: 25,
    statusDuration: 1500,
    canInterrupt: true,
    icon: "🎳",
    animation: "bowling_bash",
  },
  fire_bolt: {
    id: "fire_bolt",
    name: "Fire Bolt",
    description: "Launches fire bolts dealing 150% MATK per bolt (5 bolts)",
    damageType: "magical",
    element: "fire",
    baseDamage: 750,
    statScaling: { int: 2.0 },
    range: 7,
    castTime: 1200,
    cooldown: 3000,
    spCost: 20,
    aoe: false,
    aoeRadius: 0,
    statusEffect: "burn",
    statusChance: 20,
    statusDuration: 3000,
    canInterrupt: true,
    icon: "🔥",
    animation: "fire_bolt",
  },
  frost_diver: {
    id: "frost_diver",
    name: "Frost Diver",
    description: "Freezes the target dealing 200% MATK and immobilizing",
    damageType: "magical",
    element: "water",
    baseDamage: 200,
    statScaling: { int: 1.8 },
    range: 6,
    castTime: 800,
    cooldown: 4000,
    spCost: 25,
    aoe: false,
    aoeRadius: 0,
    statusEffect: "freeze",
    statusChance: 70,
    statusDuration: 3000,
    canInterrupt: true,
    icon: "❄️",
    animation: "frost_diver",
  },
  storm_gust: {
    id: "storm_gust",
    name: "Storm Gust",
    description: "Conjures a massive storm dealing 900% MATK in a huge AoE",
    damageType: "magical",
    element: "water",
    baseDamage: 900,
    statScaling: { int: 4.0 },
    range: 8,
    castTime: 3500,
    cooldown: 15000,
    spCost: 80,
    aoe: true,
    aoeRadius: 4,
    statusEffect: "freeze",
    statusChance: 50,
    statusDuration: 5000,
    canInterrupt: true,
    icon: "🌪️",
    animation: "storm_gust",
  },
  meteor_storm: {
    id: "meteor_storm",
    name: "Meteor Storm",
    description: "Calls meteors from the sky for massive area devastation",
    damageType: "magical",
    element: "fire",
    baseDamage: 1200,
    statScaling: { int: 5.0 },
    range: 9,
    castTime: 5000,
    cooldown: 25000,
    spCost: 120,
    aoe: true,
    aoeRadius: 5,
    statusEffect: "burn",
    statusChance: 80,
    statusDuration: 6000,
    canInterrupt: true,
    icon: "☄️",
    animation: "meteor_storm",
  },
  double_strafe: {
    id: "double_strafe",
    name: "Double Strafe",
    description: "Fires two rapid arrows dealing 260% ranged ATK",
    damageType: "ranged",
    element: "neutral",
    baseDamage: 260,
    statScaling: { dex: 2.2 },
    range: 8,
    castTime: 0,
    cooldown: 2000,
    spCost: 12,
    aoe: false,
    aoeRadius: 0,
    canInterrupt: false,
    icon: "🏹",
    animation: "double_strafe",
  },
  arrow_shower: {
    id: "arrow_shower",
    name: "Arrow Shower",
    description: "Rains arrows on a wide area dealing 200% ranged ATK",
    damageType: "ranged",
    element: "neutral",
    baseDamage: 200,
    statScaling: { dex: 1.8 },
    range: 7,
    castTime: 500,
    cooldown: 5000,
    spCost: 25,
    aoe: true,
    aoeRadius: 3,
    canInterrupt: true,
    icon: "🌧️",
    animation: "arrow_shower",
  },
  blitz_beat: {
    id: "blitz_beat",
    name: "Blitz Beat",
    description: "Falcon dives to peck a target 5 times for massive damage",
    damageType: "ranged",
    element: "wind",
    baseDamage: 500,
    statScaling: { dex: 3.0, luk: 1.5 },
    range: 6,
    castTime: 1000,
    cooldown: 7000,
    spCost: 30,
    aoe: false,
    aoeRadius: 0,
    canInterrupt: true,
    icon: "🦅",
    animation: "blitz_beat",
  },
  falcon_assault: {
    id: "falcon_assault",
    name: "Falcon Assault",
    description: "Ultimate falcon assault ignoring DEF, devastating single target",
    damageType: "ranged",
    element: "wind",
    baseDamage: 1500,
    statScaling: { dex: 6.0 },
    range: 7,
    castTime: 2000,
    cooldown: 20000,
    spCost: 100,
    aoe: false,
    aoeRadius: 0,
    statusEffect: "slow",
    statusChance: 60,
    statusDuration: 4000,
    canInterrupt: true,
    icon: "🎯",
    animation: "falcon_assault",
  },
  heal: {
    id: "heal",
    name: "Heal",
    description: "Restores HP to self or ally based on INT and DEX",
    damageType: "heal",
    element: "holy",
    baseDamage: 300,
    statScaling: { int: 2.5, dex: 0.5 },
    range: 5,
    castTime: 1000,
    cooldown: 2000,
    spCost: 15,
    aoe: false,
    aoeRadius: 0,
    canInterrupt: true,
    icon: "💚",
    animation: "heal",
  },
  blessing: {
    id: "blessing",
    name: "Blessing",
    description: "Blesses an ally, boosting STR/INT/DEX by 10 for 60s",
    damageType: "heal",
    element: "holy",
    baseDamage: 0,
    statScaling: {},
    range: 5,
    castTime: 500,
    cooldown: 5000,
    spCost: 20,
    aoe: false,
    aoeRadius: 0,
    statusEffect: "blessed",
    statusChance: 100,
    statusDuration: 60000,
    canInterrupt: true,
    icon: "✨",
    animation: "blessing",
  },
  increase_agi: {
    id: "increase_agi",
    name: "Increase AGI",
    description: "Increases ASPD and movement speed for 60s",
    damageType: "heal",
    element: "holy",
    baseDamage: 0,
    statScaling: {},
    range: 5,
    castTime: 500,
    cooldown: 5000,
    spCost: 20,
    aoe: false,
    aoeRadius: 0,
    statusEffect: "haste",
    statusChance: 100,
    statusDuration: 60000,
    canInterrupt: true,
    icon: "💨",
    animation: "increase_agi",
  },
};

// ----------------------------------------------------------
// Monster Definitions
// ----------------------------------------------------------

export const MONSTER_DEFINITIONS: Record<string, MonsterDefinition> = {
  poring: {
    id: "poring",
    name: "Poring",
    level: 1,
    hp: 50,
    atk: 7,
    def: 2,
    matk: 5,
    mdef: 3,
    moveSpeed: 50,
    atkSpeed: 1200,
    atkRange: 1,
    aggroRange: 3,
    exp: 2,
    jobExp: 1,
    element: "water",
    behavior: "passive",
    dropTable: [
      { itemId: "apple", chance: 5000, minQty: 1, maxQty: 1 },
      { itemId: "red_herb", chance: 3000, minQty: 1, maxQty: 3 },
    ],
    icon: "🟣",
    spriteKey: "poring",
    respawnTime: 15000,
  },
  zombie: {
    id: "zombie",
    name: "Zombie",
    level: 5,
    hp: 200,
    atk: 25,
    def: 10,
    matk: 5,
    mdef: 5,
    moveSpeed: 40,
    atkSpeed: 2000,
    atkRange: 1,
    aggroRange: 5,
    exp: 15,
    jobExp: 10,
    element: "shadow",
    behavior: "aggressive",
    dropTable: [
      { itemId: "rotten_bandage", chance: 4000, minQty: 1, maxQty: 3 },
      { itemId: "iron_sword", chance: 100, minQty: 1, maxQty: 1 },
    ],
    icon: "🧟",
    spriteKey: "zombie",
    respawnTime: 20000,
  },
  skeleton: {
    id: "skeleton",
    name: "Skeleton",
    level: 8,
    hp: 350,
    atk: 40,
    def: 15,
    matk: 10,
    mdef: 10,
    moveSpeed: 60,
    atkSpeed: 1600,
    atkRange: 1,
    aggroRange: 6,
    exp: 30,
    jobExp: 20,
    element: "shadow",
    behavior: "aggressive",
    dropTable: [
      { itemId: "bone", chance: 5000, minQty: 1, maxQty: 5 },
      { itemId: "chain_mail", chance: 80, minQty: 1, maxQty: 1 },
    ],
    icon: "💀",
    spriteKey: "skeleton",
    respawnTime: 25000,
  },
  orc: {
    id: "orc",
    name: "Orc Warrior",
    level: 15,
    hp: 900,
    atk: 90,
    def: 40,
    matk: 20,
    mdef: 15,
    moveSpeed: 70,
    atkSpeed: 2200,
    atkRange: 1,
    aggroRange: 7,
    exp: 100,
    jobExp: 70,
    element: "neutral",
    behavior: "aggressive",
    dropTable: [
      { itemId: "orc_fang", chance: 4500, minQty: 1, maxQty: 2 },
      { itemId: "battle_axe", chance: 150, minQty: 1, maxQty: 1 },
    ],
    icon: "👹",
    spriteKey: "orc",
    respawnTime: 35000,
  },
  drake: {
    id: "drake",
    name: "Drake",
    level: 30,
    hp: 5000,
    atk: 250,
    def: 100,
    matk: 150,
    mdef: 80,
    moveSpeed: 90,
    atkSpeed: 2000,
    atkRange: 2,
    aggroRange: 10,
    exp: 800,
    jobExp: 600,
    element: "fire",
    behavior: "aggressive",
    dropTable: [
      { itemId: "dragon_scale", chance: 3000, minQty: 1, maxQty: 2 },
      { itemId: "dragon_helm", chance: 50, minQty: 1, maxQty: 1 },
    ],
    icon: "🐉",
    spriteKey: "drake",
    respawnTime: 120000,
  },
};

// ----------------------------------------------------------
// Map Definitions
// ----------------------------------------------------------

export const MAP_DEFINITIONS: Record<string, MapDefinition> = {
  prontera: {
    id: "prontera",
    name: "Prontera",
    width: MAP_WIDTH,
    height: MAP_HEIGHT,
    tileSize: 32,
    tileType: "town",
    isSafeZone: true,
    bgm: "town_theme",
    monsterSpawns: [],
    connections: [
      { toMapId: "poring_field", fromTile: { x: 63, y: 32, mapId: "prontera" }, toTile: { x: 1, y: 32, mapId: "poring_field" } },
      { toMapId: "dungeon_01", fromTile: { x: 32, y: 63, mapId: "prontera" }, toTile: { x: 32, y: 1, mapId: "dungeon_01" } },
    ],
  },
  poring_field: {
    id: "poring_field",
    name: "Poring Fields",
    width: MAP_WIDTH,
    height: MAP_HEIGHT,
    tileSize: 32,
    tileType: "grass",
    isSafeZone: false,
    bgm: "field_theme",
    monsterSpawns: [
      { monsterId: "poring", count: 20, area: { x: 2, y: 2, w: 60, h: 60 } },
      { monsterId: "zombie", count: 8, area: { x: 20, y: 20, w: 40, h: 40 } },
    ],
    connections: [
      { toMapId: "prontera", fromTile: { x: 0, y: 32, mapId: "poring_field" }, toTile: { x: 62, y: 32, mapId: "prontera" } },
      { toMapId: "orc_village", fromTile: { x: 63, y: 32, mapId: "poring_field" }, toTile: { x: 1, y: 32, mapId: "orc_village" } },
    ],
  },
  orc_village: {
    id: "orc_village",
    name: "Orc Village",
    width: MAP_WIDTH,
    height: MAP_HEIGHT,
    tileSize: 32,
    tileType: "stone",
    isSafeZone: false,
    bgm: "combat_theme",
    monsterSpawns: [
      { monsterId: "orc", count: 15, area: { x: 5, y: 5, w: 54, h: 54 } },
      { monsterId: "skeleton", count: 10, area: { x: 10, y: 10, w: 44, h: 44 } },
    ],
    connections: [
      { toMapId: "poring_field", fromTile: { x: 0, y: 32, mapId: "orc_village" }, toTile: { x: 62, y: 32, mapId: "poring_field" } },
      { toMapId: "dragon_lair", fromTile: { x: 32, y: 63, mapId: "orc_village" }, toTile: { x: 32, y: 1, mapId: "dragon_lair" } },
    ],
  },
  dungeon_01: {
    id: "dungeon_01",
    name: "Prontera Dungeon",
    width: MAP_WIDTH,
    height: MAP_HEIGHT,
    tileSize: 32,
    tileType: "dungeon",
    isSafeZone: false,
    bgm: "dungeon_theme",
    monsterSpawns: [
      { monsterId: "skeleton", count: 20, area: { x: 2, y: 2, w: 60, h: 60 } },
    ],
    connections: [
      { toMapId: "prontera", fromTile: { x: 32, y: 0, mapId: "dungeon_01" }, toTile: { x: 32, y: 62, mapId: "prontera" } },
    ],
  },
  dragon_lair: {
    id: "dragon_lair",
    name: "Dragon's Lair",
    width: MAP_WIDTH,
    height: MAP_HEIGHT,
    tileSize: 32,
    tileType: "lava",
    isSafeZone: false,
    bgm: "boss_theme",
    monsterSpawns: [
      { monsterId: "drake", count: 3, area: { x: 15, y: 15, w: 34, h: 34 } },
      { monsterId: "orc", count: 10, area: { x: 2, y: 2, w: 60, h: 60 } },
    ],
    connections: [
      { toMapId: "orc_village", fromTile: { x: 32, y: 0, mapId: "dragon_lair" }, toTile: { x: 32, y: 62, mapId: "orc_village" } },
    ],
  },
};

// ----------------------------------------------------------
// EXP Table (base levels 1-99)
// ----------------------------------------------------------

function generateExpTable(): LevelData[] {
  const table: LevelData[] = [];
  for (let lvl = 1; lvl <= 99; lvl++) {
    // Ragnarok-inspired exponential curve
    const expToNext = Math.floor(10 * Math.pow(lvl, 2.3) + 50 * lvl);
    const expRequired = lvl === 1 ? 0 : table[lvl - 2].expRequired + table[lvl - 2].expToNext;
    table.push({ level: lvl, expRequired, expToNext });
  }
  return table;
}

export const EXP_TABLE = generateExpTable();

// ----------------------------------------------------------
// Item Definitions (base items)
// ----------------------------------------------------------

export const ITEM_NAMES: Record<string, string> = {
  apple: "Apple",
  red_herb: "Red Herb",
  rotten_bandage: "Rotten Bandage",
  iron_sword: "Iron Sword",
  bone: "Bone",
  chain_mail: "Chain Mail",
  orc_fang: "Orc Fang",
  battle_axe: "Battle Axe",
  dragon_scale: "Dragon Scale",
  dragon_helm: "Dragon Helm",
};

// ----------------------------------------------------------
// Status Effect Colors (for PixiJS UI)
// ----------------------------------------------------------

export const STATUS_COLORS: Record<string, number> = {
  burn: 0xff4400,
  freeze: 0x4488ff,
  stun: 0xffcc00,
  poison: 0x44ff44,
  slow: 0xaaaaaa,
  blessed: 0xffff88,
  haste: 0x88ffff,
};

// ----------------------------------------------------------
// Damage Number Colors
// ----------------------------------------------------------

export const DAMAGE_COLORS = {
  physical: 0xffffff,
  magical: 0x8888ff,
  heal: 0x44ff88,
  miss: 0xaaaaaa,
  crit: 0xffcc00,
};

// ----------------------------------------------------------
// Starting Stats per Job
// ----------------------------------------------------------

export function getStartingStats(jobId: string) {
  const defaults = { str: 1, int: 1, dex: 1, vit: 1, agi: 1, luk: 1 };
  switch (jobId) {
    case "swordsman":
    case "knight":
    case "lord_knight":
      return { ...defaults, str: 8, vit: 6, agi: 5 };
    case "mage":
    case "wizard":
    case "high_wizard":
      return { ...defaults, int: 9, dex: 6, agi: 4 };
    case "archer":
    case "hunter":
    case "sniper":
      return { ...defaults, dex: 9, agi: 7, luk: 5 };
    default:
      return defaults;
  }
}

export function calculateDerived(stats: { str: number; int: number; dex: number; vit: number; agi: number; luk: number }, level: number, baseHp: number, baseSp: number) {
  return {
    maxHp: baseHp + stats.vit * 10 + level * 20,
    hp: baseHp + stats.vit * 10 + level * 20,
    maxSp: baseSp + stats.int * 5 + level * 8,
    sp: baseSp + stats.int * 5 + level * 8,
    atk: stats.str * 4 + stats.dex * 1 + level * 2,
    matk: stats.int * 5 + level * 2,
    def: stats.vit * 3 + level * 1,
    mdef: stats.int * 2 + stats.vit * 1,
    flee: stats.agi * 3 + level * 1,
    hit: stats.dex * 4 + level * 2,
    aspd: Math.min(190, 100 + stats.agi * 2),
    critRate: Math.floor(stats.luk / 3) + 1,
    critDmg: 150,
  };
}
